.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. refnet_qt test_refnet_qt
clean: FORCE
	$(MAKE) -C .. refnet_qt_clean test_refnet_qt_clean
check: FORCE
	$(MAKE) -C .. test_refnet_qt_check
refnet-qt refnet-qt.exe: FORCE
	 $(MAKE) -C .. refnet_qt
